// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const iconIdList = [
  'add',
  'adjust',
  'anchor',
  'arrow_back',
  'arrow_right_alt',
  'change_history',
  'check_circle',
  'check',
  'chevron_left',
  'chevron_right',
  'circle',
  'close',
  'content_copy',
  'delete',
  'download',
  'edit',
  'error',
  'event',
  'file_save',
  'info',
  'keyboard_arrow_down',
  'keyboard_arrow_up',
  'lock',
  'logout',
  'more_vert',
  'person',
  'radio_button_checked',
  'radio_button_unchecked',
  'sailing',
  'settings_input_antenna',
  'stylus',
  'timeline',
  'warning',
] as const;
export type IconId = (typeof iconIdList)[number];
