name: CI

on:
  - pull_request

jobs:
  check-pr-title:
    name: Conventional Commit PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: true
          scopes: |
            base
            kart
  check-i18n:
    name: Check i18n
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '24.x'
      - run: npx @kystverket/sprak-cli check --config ./base/styrbord.sprak.json
  run-linters:
    name: Pretty / Lint / Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '24.x'
      - name: npm ci
        run: |
          printf "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN\n@kystverket:registry=https://npm.pkg.github.com/" > .npmrc
          npm ci --ignore-scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run lint:check -w base
      - run: npm run pretty:check -w base
      - run: npm run build -w base
